---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/10/23 14:52
---

---@class FairyGUI.Utils:namespace
Utils = {name = 'Utils'}

require('Utils.Html.IHtmlObject')
require('Utils.Html.IHtmlPageContext')
require('Utils.Html.HtmlButton')
require('Utils.Html.HtmlElement')
require('Utils.Html.HtmlImage')
require('Utils.Html.HtmlInput')
require('Utils.Html.HtmlLink')
require('Utils.Html.HtmlPageContext')
require('Utils.Html.HtmlParseOptions')
require('Utils.Html.HtmlParser')
require('Utils.Html.HtmlSelect')

FairyGUI.Utils = Utils
return Utils