---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/3 15:30
---

---@class love.Object
local M = {}

---Immediately destroys the object's Lua reference
---API: 11.0
---Synopsis: success = Object:release( )
---@return boolean
function M:release() end

---Gets the type of the object as a string.
---Synopsis: type = Object:type()
---@return string
function M:type() end

--[[
image = love.graphics.newImage("test.png")
print(image:typeOf("Object")) -- outputs: true
print(image:typeOf("Drawable")) -- outputs: true
print(image:typeOf("Image")) -- outputs: true
print(image:typeOf("MouseJoint")) -- outputs: false
]]
---@param name string @The name of the type to check for.
---@return boolean @True if the object is of the specified type, false otherwise.
function M:typeOf(name) end

love.Object = M
return M