---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/11/19 19:15
---

local Class = require('libs.Class')

local Object = Love2DEngine.Object

---@class Love2DEngine.TextAsset:Love2DEngine.Object
---@field text string
---@field bytes byte[]
local TextAsset = Class.inheritsFrom('TextAsset', nil, Object)

--TODO: Love2DEngine.TextAsset

Love2DEngine.TextAsset = TextAsset
return TextAsset

