---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/12/3 15:30
---

---@class love.Object.Font:love.Object
local M = {}

---Gets the ascent of the Font in pixels.
---@return number @The ascent of the Font in pixels.
function M:getAscent()
end
---Gets the baseline of the Font in pixels.
---@return number The baseline of the Font in pixels.
function M:getBaseline()
end
---Gets the DPI scale factor of the Font.
function M:getDPIScale()
end
---Gets the descent of the Font in pixels.
function M:getDescent()
end
---Gets the filter mode for a font.
function M:getFilter()
end
---Gets the height of the Font in pixels.
function M:getHeight()
end
---Gets the line height.
function M:getLineHeight()
end
---Determines the width of the given text.
function M:getWidth()
end
---Gets formatting information for text, given a wrap limit.
function M:getWrap()
end
---Gets whether the Font can render a character or string.
function M:hasGlyphs()
end
---Sets other Fonts to use if this Font doesn't have a specific character.
function M:setFallbacks()
end
---Sets the filter mode for a font.
function M:setFilter()
end
---Sets the line height.
function M:setLineHeight()
end

love.Object.Font = M
return M